#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"

if ! command -v docker >/dev/null 2>&1; then
  printf 'Docker is required. Install Docker Engine and Docker Compose, then run this command again.\n' >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  printf 'Docker Compose v2 is required.\n' >&2
  exit 1
fi

if [[ ! -f "$ENV_FILE" ]]; then
  db_password="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
  setup_token="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/start.sh. Do not commit this file.
POSTGRES_PASSWORD=$db_password
DATABASE_URL=postgresql+psycopg://igoragent:$db_password@postgres:5432/igoragent
REDIS_URL=redis://redis:6379/0
IGORAGENT_LOCAL_MODE=true
IGORAGENT_COOKIE_SECURE=false
IGORAGENT_SETUP_TOKEN=$setup_token
NEXT_PUBLIC_API_URL=/api
EOF
  chmod 600 "$ENV_FILE"
  printf 'Created protected local configuration at %s\n' "$ENV_FILE"
fi

cd "$PROJECT_DIR"
docker compose --env-file "$ENV_FILE" -f infra/docker-compose.local.yml up --build -d

printf '\nIgorAgent is starting. Open: http://localhost:3000\n'
printf 'On the first visit, create the dashboard password and complete onboarding.\n'
printf 'Check status with: docker compose -f infra/docker-compose.local.yml ps\n'
